/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Presentation.Frames;

import BE.Fireman;
import BLL.Fireman_AccessLink;
import java.awt.event.MouseAdapter;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Poul Nielsen
 */
public class TimeSheetOverview extends javax.swing.JPanel {
    Fireman_AccessLink fal;
    DefaultListModel firemenModel;
    /**
     * Creates new form TimeSheetOverview
     */
    public TimeSheetOverview() {
        firemenModel = new DefaultListModel();
        
        try {
            fal = new Fireman_AccessLink();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Der er problemer med databasen");
        }
        initComponents();
        populateFiremanList();
        
        jLFiremanList.addMouseListener(new MouseAdapter() {
});
    }
    
    
    private void populateFiremanList()
    {
        try {
            ArrayList<Fireman> fireman = fal.getAllFiremen();
            
            for(Fireman a : fireman)
            {
                firemenModel.addElement(a.getFirstName()+" "+a.getLastName());
                jLFiremanList.setModel(firemenModel);
            }
       } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Der er problemer med databasen " + ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFiremanPanel = new javax.swing.JPanel();
        jSFiremanScrollpane = new javax.swing.JScrollPane();
        jLFiremanList = new javax.swing.JList();
        lblFiremen = new javax.swing.JLabel();
        jPtableholder = new javax.swing.JPanel();
        jStable = new javax.swing.JScrollPane();

        jSFiremanScrollpane.setViewportView(jLFiremanList);

        lblFiremen.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lblFiremen.setText("Brandmænd");

        javax.swing.GroupLayout jpFiremanPanelLayout = new javax.swing.GroupLayout(jpFiremanPanel);
        jpFiremanPanel.setLayout(jpFiremanPanelLayout);
        jpFiremanPanelLayout.setHorizontalGroup(
            jpFiremanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFiremanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFiremanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSFiremanScrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jpFiremanPanelLayout.createSequentialGroup()
                        .addComponent(lblFiremen)
                        .addGap(0, 95, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpFiremanPanelLayout.setVerticalGroup(
            jpFiremanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFiremanPanelLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(lblFiremen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSFiremanScrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPtableholderLayout = new javax.swing.GroupLayout(jPtableholder);
        jPtableholder.setLayout(jPtableholderLayout);
        jPtableholderLayout.setHorizontalGroup(
            jPtableholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPtableholderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jStable, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPtableholderLayout.setVerticalGroup(
            jPtableholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPtableholderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jStable, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpFiremanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPtableholder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPtableholder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpFiremanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jLFiremanList;
    private javax.swing.JPanel jPtableholder;
    private javax.swing.JScrollPane jSFiremanScrollpane;
    private javax.swing.JScrollPane jStable;
    private javax.swing.JPanel jpFiremanPanel;
    private javax.swing.JLabel lblFiremen;
    // End of variables declaration//GEN-END:variables
}
